version: "3.9"
services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./src/main/resources:/var
    restart: unless-stopped

  postgres:
    image: postgres:13.3
    volumes:
      - ./docker/.data/postgres:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    restart: unless-stopped