server:
  port: 8080

spring:
  config:
    import:
      optional:file:.env[.properties]
  mail:
    host: imap.gmail.com
    port: 587
    username: monsystem0@gmail.com
    password: bwvnbfygfiuytlli
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  enable-spring-security: true
  show-actuator: true
